### ISSUE TITLE
Edit Entries: Default selection in location widget

### ISSUE THREAD

**Issue by patricechataigner** [the-deep/deeper#137]
Is it possible to set a default location as "Country" in the location widget (a bit like for the scale widget where we can set a default value that will always appear. The reason is that for the moment, if we dont use the location widget for an entry, the admin level stay blank in the excel export, while it should be at a minimum the country. thanks!

**Comment by eoglethorpe** [comment]
i think we should fully resolve this by doing the proper admin area linking (either through polygon inclusion, or ensuring the parent_code fields are all there... this would take a good bit of work).

open to feedback.

**Comment by eoglethorpe** [comment]
@amarshahi @frozenhelium if we do the polygon linking properly, does this mean that it would appear in the excel export?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , could you elaborate on what you mean?

**Comment by eoglethorpe** [comment]
let's discuss on wed, i'll add a note on comms

**Comment by eoglethorpe** [comment]
@patricechataigner how do you want to handle when there are more than countries in an project?
