### ISSUE TITLE
Analysis Framework: Matrix 1D: Color in edit mode

### ISSUE THREAD

**Issue by patricechataigner** [the-deep/deeper#139]
Background colour is not working in the 1D matrix

**Comment by eoglethorpe** [comment]
ooooo i don't know. definitely not 1, but i'm between 2 and 3. what about the label cell AND value cells colored?

**Comment by eoglethorpe** [comment]
veto!!!!

**Comment by patricechataigner** [comment]
I soooooo over veto you. Lets go for 1!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le jeu. 31 janv. 2019 à 15:06, Ewan Oglethorpe <notifications@github.com> a
écrit :

**Comment by eoglethorpe** [comment]
*grumbles*

Please note that we had a phone call where I allowed Patrice to over veto me

**Comment by eoglethorpe** [comment]
@patricechataigner I'M RE-VETOING YOU.

what if we only had colors for the label columns for 1D AND 2D matrices? I think it'd make the 2D matrix cleaner. if we did this, then i'd say we choose option 2

**Comment by eoglethorpe** [comment]
@frozenhelium when you have a minute could you play around with the options i mentioned above?

**Comment by tnagorra** [comment]
@eoglethorpe do you mean something like this?
![grim_2019-03-08-182703](https://user-images.githubusercontent.com/4928045/54029249-e0f99700-41cf-11e9-9831-0d4131ef74cf.png)

**Comment by eoglethorpe** [comment]
@tnagorra yeah just like that. i think it works nicely for the 1D, although i'm concerned is a bit drab for the 2D, in particuarl as we already have the grey background. 

what about invetering the white/grey in the 2D matrix?

i think it's important we get this right, as the 2D matrix is the crux of the tagging process

**Comment by tnagorra** [comment]
Something like this?
![54029249-e0f99700-41cf-11e9-9831-0d4131ef74cf](https://user-images.githubusercontent.com/4928045/54142283-79ea1580-444f-11e9-994c-cf7edc4c88a8.png)

**Comment by eoglethorpe** [comment]
yeah that’s what I had in mind, dunno how elegant it is. i’ve asked @pprabesh @amarshahi to follow up further on this

**Comment by eoglethorpe** [comment]
on hold pending DFS

**Comment by patricechataigner** [comment]
yeah let us come back with a solution on this...
