### ISSUE TITLE
Arrows and lines for fields

### ISSUE THREAD

**Issue by patricechataigner** [the-deep/deeper#171]
Hello guys! Congrats and champagne for solving all the issues (or is it a bug)`?

My first new proposed issue is about all DEEP fields. currently we have a thick grey line underlying the field to fill and an arrow on the extreme right, like this:
![image](https://user-images.githubusercontent.com/15996586/52129575-227aad80-2638-11e9-83ac-ab2f18ab2bb2.png)

I would suggest we use a less thick and maybe lighter grey line and get the arrow much closer from the field title, so we dont have those long lines. please implement across all the deep website? thanks in advance and have a nice week end!!

**Comment by eoglethorpe** [comment]
@patricechataigner we've udpated this anyways - it'll be up in the next minor release in ~2 weeks

**Comment by eoglethorpe** [comment]
@patricechataigner
