### ISSUE TITLE
Analysis Framework: New view with faster selection of AF options. (Virtualization) Currently takes ~10 seconds to load.

### ISSUE THREAD

**Issue by pprabesh** [the-deep/deeper#173]

**Comment by eoglethorpe** [comment]
what's the discussion?

**Comment by tnagorra** [comment]
Related to https://github.com/the-deep/deeper/issues/177

**Comment by pprabesh** [comment]
About when it should go into maintenance when approved by you. 
We could go with virtualized list.(or just search options like in User Panel) Or if you have any other cool ideas.

**Comment by eoglethorpe** [comment]
i think we should hold off on this as we're discussing touching up the AF page
