### ISSUE TITLE
Assessment registry - Partner and country list

### ISSUE THREAD

**Issue by patricechataigner** [the-deep/deeper#183]
OK so i have been giving thoughts to the problem of th elong list of partners from which to chose. best colution i could find is the skype option to add members to a group. you can type the name in the search field and then the realted options appear below, you can select the one you are interested on and continue with selecting others
![image](https://user-images.githubusercontent.com/15996586/52623286-421d9b80-2eac-11e9-9f14-1faab75aa148.png)

let me know what you think

**Comment by eoglethorpe** [comment]
yeah i dig it. would need to think of how to handle long text tho - maybe have a cutoff?

**Comment by eoglethorpe** [comment]
![image](https://user-images.githubusercontent.com/9661732/52743555-47f8a700-2fa8-11e9-9ff8-e26889e79fc8.png)

**Comment by eoglethorpe** [comment]
i'd be open to changing all dropdown lists to having this behavior
