### ISSUE TITLE
edit entries: add warning in screenshot function that plugin must be installed if not installed

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#185]
bad wording. see: 

https://github.com/the-deep/deeper/issues/185

**Comment by tnagorra** [comment]
Maybe disable the screenshot button and have the warning popup as tooltip?

**Comment by eoglethorpe** [comment]
@tnagorra i'm down with the tooltip, however my concern until we have our own custom tooltip is that it takes some time to appear and to the user it just seems like a broken feature. could you have the tooltip be triggered by clicking the camera icon?

**Comment by eoglethorpe** [comment]
wording: In order to use the screenshot functionality, you must have the Chrome extension installed. You can download it from the Chrome store [here].

**Comment by tnagorra** [comment]
There is already a mechanism to show warning that the extension must be installed before screenshot can be used.
The warning is shown as Toast when user clicks on the button and the extension has not been installed.

**Comment by eoglethorpe** [comment]
yeah i see that warning - has it always been there? not sure why it didn't appear previously.

could we just update the wording for that popup? tnx

**Comment by tnagorra** [comment]
This took 1 hour.

**Comment by amarshahi** [comment]
Hours: 1
