### ISSUE TITLE
Export in excel - strange signs not exported

### ISSUE THREAD

**Issue by patricechataigner** [the-deep/deeper#190]
Dear all, 
i have a framework with a single drop down menu which display options such as < 5 years, >30 years, etc. when exporting in excel the results is like this:
![image](https://user-images.githubusercontent.com/15996586/52711036-1cb68d80-2f91-11e9-8ef8-3cdd42aef8c4.png)

I think the problem comes from the sign > or <
the project is https://beta.thedeep.io/projects/740/exports/

thanks if we can solve the issue soon!

**Comment by eoglethorpe** [comment]
will fix. @frozenhelium can we push a hotfix?

**Comment by thenav56** [comment]
Fixed and pushed to beta.

**Comment by thenav56** [comment]
Fixed and pushed to beta.

**Comment by eoglethorpe** [comment]
thanks @thenav56. @patricechataigner can you verify it's to your liking?
