### ISSUE TITLE
Tabular: Admin areas in import

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#191]
Right now we have just the ability to select an admin level, on the call we discussed showing users which area names are in which levels.

I thought about this and I don't think it's a graceful solution. Could we please give users the ability to select from a dropdown list that names the individual admin areas in their project?

Similar to how it works in the tagging page. Would be nice to have multi select dropdown for instances where there is more than one region listed, but for now can we do the slash method?

Country 1 / Name 1
...
Country n / Name n

Then whichever areas are selected, that's what used in identifying the names.

![image](https://user-images.githubusercontent.com/9661732/52742526-e9322e00-2fa5-11e9-99c6-dc0bbba1ce4c.png)

**Comment by AdityaKhatri** [comment]
This way, the user could be able to select multiple admin levels of the same region and also different admin levels of different regions of the project.This won't work in accord to our

**Comment by eoglethorpe** [comment]
ok per our call let's revert to original plan with one selection and overview page
