### ISSUE TITLE
Tabular: Inform last time saved

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#193]
In the bulk upload modal, i see that it autosaves which is cool. Can we have a field that says "Last saved at XX" (and then displays it in browser's local time?)

Right now it's not too clear if new changes have been saved or not.

**Comment by eoglethorpe** [comment]
hmmm i acutally think we should do this for all parts of the site that are autosaved. thoughts?

**Comment by tnagorra** [comment]
All of the actions are saved in foreground, only the filters and colum width are saved in the background which are not cirtical information.


No other part of deep implements background saving.

**Comment by eoglethorpe** [comment]
@tnagorra i don't think you get what i'm saying. we're autosaving, and we should tell users we're autosaving. it doesn't matter if it's in the foreground or background

**Comment by eoglethorpe** [comment]
there are plenty of other parts of DEEP that implement autosaving (be it foreground or otherwise)

**Comment by tnagorra** [comment]
We have visual indicators for anything that is saved in tabular in foreground.
We have "Saving..." for anything that is saved in the background. (these are table settings that aren't very crucial)

Can you tell me what other parts of DEEP implement auto-saving to the server?

**Comment by eoglethorpe** [comment]
when in doubt, do it how Google Docs does it :D

as for the exact functions that we should tell users we're saving for, i'd need to check on alpha however i don't see the tabular feature up right now? 

i'm not sure about serverside autosaving, you guys are better suited to answer that. i was just referring to any kind of autosaving, regardless of it its client/serverside

**Comment by tnagorra** [comment]
I think we can show _'Last saved at' message_ after response from any of the requests in tabular.

Auto-saving on client side is instantaneous so we may not need that message if we are saving it client side.

**Comment by eoglethorpe** [comment]
i think you need to look at it from the end user's point of view and not as a developer; if a user makes a change they'll want to know if it's been saved or not or if they need to save it themselves... a user doesn't care how the request is handled.

we should go ahead and add this feature for anything that triggers a saving mechanism. can we ensure the time shown is local user time?

**Comment by tnagorra** [comment]
I agree that we should think it from the end user's perspective, so I suggested to show "Saving.." message for any request.

We can ensure that the time shown is local user time.

By saving mechanism, what are you actually referring to? Can you provide us with some example?

**Comment by eoglethorpe** [comment]
let’s discuss on our next call?
