### ISSUE TITLE
Notification - Reject or add

### ISSUE THREAD

**Issue by patricechataigner** [the-deep/deeper#201]
When we receive a notification for somebdoy who wants to join  a project, and we click on add or reject, nothing happen. would be good that we see a sentence saying: You rejected XX on date XX.XX.XXXX or something like this. for the moment we dont know what happen after we click. cheers!

Correction: So this actually happen ( it goes from the top rows  "action" to down rows "notification", but not immediately. Is there any way to make the process quicker so we immediately see the action shifting to notification?

**Comment by eoglethorpe** [comment]
i think this would be a good fix; what's the LoE? @frozenhelium

**Comment by frozenhelium** [comment]
I think it's an easy fix, will implement it.

**Comment by eoglethorpe** [comment]
cool - maybe some kind of ephemeral highlighting?

**Comment by eoglethorpe** [comment]
@frozenhelium @amarshahi ?

**Comment by frozenhelium** [comment]
How urgent is this? Should we put this to this month's maintenance?

**Comment by eoglethorpe** [comment]
it’s not urgent, but if you have time this month and it’s easy we can do it

**Comment by tnagorra** [comment]
Realated to https://github.com/the-deep/deeper/issues/135

**Comment by frozenhelium** [comment]
Estimated hours: 8
