### ISSUE TITLE
Chrome Extension Policy

### ISSUE THREAD

**Issue by thenav56** [the-deep/deeper#202]
![image](https://user-images.githubusercontent.com/7059255/52956665-f5f4be80-33b7-11e9-8eb7-42fbf7937361.png)

**Comment by eoglethorpe** [comment]
weird, we have the screenshots. maybe it needs more of a description?

for the overview can we do:

tagline: Easily add leads to your DEEP project from the comfort of your own browser.
overview: 

Using this extension you can add URLs directly to your DEEP project without having to deal with copying and pasting any URLs.

The extension will also automatically extract information for fields such as title, publisher and date (this works on most websites, however some are not entirely compatible).

Any questions? Contact admin@thedeep.io 

Need help getting started with DEEP? Checkout our user guide [https://deephelp.zendesk.com/hc/en-us/categories/360000874911-DEEP-User-Guide]

**Comment by eoglethorpe** [comment]
@thenav56 can you please add admin@thedeep.io to the list of accts that are associated with the plugin? ie this email should come to that address. tnx

**Comment by AdityaKhatri** [comment]
@eoglethorpe this has been completed and accepted by chrome web store.

**Comment by eoglethorpe** [comment]
dhanyabad

**Comment by AdityaKhatri** [comment]
Haha
