### ISSUE TITLE
entries tagging: nlp: no suggestions for categorization

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#228]
https://beta.thedeep.io/projects/397/leads/432/edit-entries/#/overview

@bewakes

**Comment by bewakes** [comment]
I cannot access that page @eoglethorpe , but I will look into the issue.

**Comment by eoglethorpe** [comment]
you can just add yourself to the project?

**Comment by eoglethorpe** [comment]
@bewakes @amarshahi ?

**Comment by bewakes** [comment]
@eoglethorpe, the issue is that, sometimes, requests sent to DEEPL by DEEP server fail so DEEP won't get the classified_doc_id. I'll write a script to re-send requests to DEEPL and this will be fixed.
