### ISSUE TITLE
extension: error

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#229]
![image](https://user-images.githubusercontent.com/9661732/53570776-5234ac80-3b35-11e9-84ef-0b9d3f4e2563.png)

**Comment by frozenhelium** [comment]
We have to further investigate on this issue. In general note, I think we should add sentry to the extension as well.

**Comment by eoglethorpe** [comment]
@frozenhelium @amarshahi ?

**Comment by frozenhelium** [comment]
Cannot replicate the issue. Was the extension installed from your local disk?

**Comment by eoglethorpe** [comment]
negatory. now that i've deleted and reinstalled it's working, but am concerned that it could be an issue for other users

**Comment by frozenhelium** [comment]
https://github.com/the-deep/deeper/issues/313 should help detect if any other users run into such issue.
