### ISSUE TITLE
connector: empty values from WFP portal

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#230]
https://beta.thedeep.io/connectors/99/

**Comment by eoglethorpe** [comment]
@amarshahi @frozenhelium ?

**Comment by AdityaKhatri** [comment]
We'll need to check on WFP connector.
Could you let us know the urgency of this and we'll prioritize accordingly?

**Comment by eoglethorpe** [comment]
this is low priority but also feeds into the other issue of proactively identifying when APIs are down

**Comment by AdityaKhatri** [comment]
Related to https://github.com/the-deep/deeper/issues/703
