### ISSUE TITLE
projects page: thousands separator 

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#232]
really?

![image](https://user-images.githubusercontent.com/9661732/53581476-a34f9b00-3b4b-11e9-94cc-7b885b864aa7.png)

**Comment by eoglethorpe** [comment]
also not sure why 'created by' is out of alignment

**Comment by frozenhelium** [comment]
I guess, there were only three numbered count for entries while we were testing and missed it. This will be fixed soon.

**Comment by eoglethorpe** [comment]
@frozenhelium @amarshahi this shoudl be closed right?

**Comment by AdityaKhatri** [comment]
Yes
