### ISSUE TITLE
LeadAdd:Connector: hanging on large import [OHCHR]

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#238]
connector: Thailand_EMMfeed_SA_framework
behavior: "once we selected save>all, the wheel started spinning and articles were being added, we could see the green circle one by one but then it lagged at one point in time and the page automatically crashed, we tried it again , the same thing happened".
user: followup with Venkatesh in Beta testing Skype group

**Comment by tnagorra** [comment]
This issue was replicated on kriti's PC as well.
Looks like a memory leak problem with the redux-persist library.

**Comment by eoglethorpe** [comment]
@tnagorra cool. how hard is the fix?

**Comment by tnagorra** [comment]
We cannot fix the memory leak problem, but we can have a workaround for it.
The problem arises when we call large number of actions to redux.

There can be two solutions:
1. Throttle the action / Call actions in batch. (Action to update progress of upload, Action to add multiple leads)
2. Create smaller redux persistence units. This approach will take some appreciable time but is the better solution.

**Comment by frozenhelium** [comment]
Problem with react-redux-persist library:
The library serializes the whole tree before saving it in localstorage/localforage. When multiple actions are dispatched within a short time, there exists multiple instances of serialized state (maybe not properly garbage collected)  and take up a lot of memory.
In our case, the multiple actions to update the progress bar of each upload looks like a possible cause of the problem. But, looks like it is not the only reason the page crashes.

One solution would be to throttle and merge similar actions into a bulk action. This will solve the issue when multiple files are uploaded. But, this will not solve similar future issue. This will take about 32 hours of work.

Another solution would be to create small manageable persistence unit (This is a new feature in react-redux-persist which wasn’t available when we were starting on deep). With independent persistence unit, small chunk of memory can be serialized and saved to localstorage/localforage. This looks like a better solution to the problem.  This will take about 200 hours of work.

**Comment by eoglethorpe** [comment]
thanks for the details and letting me know the estimates. let’s table it for now and come back when we have mo’ cash.
