### ISSUE TITLE
Bulk upload: dual lead preview

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#281]
leads were uploaded from bulk upload. seems there's a dual one listed in the upload.

when i select one of the leads in bulk upload, it selects both

![image](https://user-images.githubusercontent.com/9661732/54614471-c4295300-4a5c-11e9-8bf5-59919e8e15c7.png)

![image](https://user-images.githubusercontent.com/9661732/54614447-b83d9100-4a5c-11e9-8b1b-df83acf07beb.png)

**Comment by AdityaKhatri** [comment]
Related to: https://github.com/the-deep/deeper/issues/279

**Comment by amarshahi** [comment]
Hours: 3
