### ISSUE TITLE
Project panel: incorrect user count

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#283]
1) create project
2) add users
3) (without refreshing) look at project panel. in this project i had 8 users, but it shows 1
4) is correct when i refresh

![image](https://user-images.githubusercontent.com/9661732/54679030-a87a8700-4b06-11e9-89ba-ab95feaca9ac.png)

**Comment by eoglethorpe** [comment]
@amarshahi @AdityaKhatri ?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , we'll retrigger the api pull.
It will be fixed in the next deployment.

**Comment by eoglethorpe** [comment]
20h?? let's go for the first option

**Comment by AdityaKhatri** [comment]
Sure, it will be deployed with the next release.

**Comment by amarshahi** [comment]
Hours: 0.75
