### ISSUE TITLE
Join Request: Logic for already accepted request in email

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#285]
1): user requests to join project
2): request granted by another admin
3): user clicks on 'accept' link in email
4): told invalid request. should say that request has already been dealt with

![image](https://user-images.githubusercontent.com/9661732/54696992-1afe5d80-4b2d-11e9-8e0b-406a966dd109.png)

**Comment by thenav56** [comment]
@eoglethorpe
Right now the token for project request accept/reject are generated using the attributes of the project join request and responsible user id. If one of the attributes are changed, the token gets invalid.

So, right now we only provide information/action when the token is valid.

I suggest we show message like
"Oops, project join request is expired or already accepted/rejected."

Let me know if you have specific wording.

**Comment by eoglethorpe** [comment]
hmmm ok that's cool. let's just change the wording to:

"Oops, project join request is expired or already accepted/rejected. Please view your notifications panel in DEEP for further details."

**Comment by eoglethorpe** [comment]
@thenav56 @AdityaKhatri @amarshahi latest here?

**Comment by thenav56** [comment]
@eoglethorpe we will add this to hotfix.

**Comment by bewakes** [comment]
@eoglethorpe ,
![image](https://user-images.githubusercontent.com/5417640/55529525-8ade1d80-56c1-11e9-9e23-d3553eada11b.png)
this is the current view.

**Comment by amarshahi** [comment]
Hours: 1
