### ISSUE TITLE
Lead grid view: No previews

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#288]
https://beta.thedeep.io/projects/321/leads/#/grid

![image](https://user-images.githubusercontent.com/9661732/54701307-07ef8b80-4b35-11e9-8f4c-2b4e97ca2152.png)

**Comment by timilsinabishal** [comment]
Looks like these leads were created before implementing the grid feature. We also have a command to generate a thumbnail for those, it should fix no preview issue.

**Comment by eoglethorpe** [comment]
@amarshahi did we run this script?

**Comment by amarshahi** [comment]
@timilsinabishal do you have the migrations for generating the thumbnails or just the command line?

**Comment by timilsinabishal** [comment]
@amarshahi there is a command for it. `./manage.py generate_thumbnail --existing`

**Comment by amarshahi** [comment]
Great, Thanks! We will run this command on our next deployment and this should fix the problem.
cc @timilsinabishal @eoglethorpe

**Comment by eoglethorpe** [comment]
@amarshahi latest?

**Comment by AdityaKhatri** [comment]
This will be fixed on our next deployment, we will keep you updated on this.

**Comment by eoglethorpe** [comment]
when’s that?

**Comment by eoglethorpe** [comment]
need to see in production. also this is an opt-in feature or what?

**Comment by eoglethorpe** [comment]
still missing for quite a few
