### ISSUE TITLE
Tabular: World cloud being a word cloud

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#291]
Right now the word cloud is a string cloud - it doesn't tokenize and take individual strings

**Comment by AdityaKhatri** [comment]
@eoglethorpe , what do we do in cases such as 'Democratic Republic of Congo', it would tokenize it and wouldn't make sense right?
Let us know your thoughts, and we will work on it accordingly.

**Comment by eoglethorpe** [comment]
no it wouldn't make sense and good point but that's the downside of a wordcloud - the pros outweigh the cons tho. let's go for ngram 1 of this
