### ISSUE TITLE
Country profile: Fix wording for blank values

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#295]
"Selected country not found"

![image](https://user-images.githubusercontent.com/9661732/54824856-6e4aea00-4cac-11e9-83c8-aad123d43fe0.png)

**Comment by amarshahi** [comment]
Hours Spent: 0.1 hours

**Comment by amarshahi** [comment]
+ 0.4 hours after assessing it again.

**Comment by eoglethorpe** [comment]
@amarshahi what do you mean?
