### ISSUE TITLE
Issues with viewing edit entries and simplified text extraction

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#297]
UPDATE: user reports that the edit entries functionality now works for a new project, so maybe it's isolated to this project and maybe others?

Seems like the edit entries page isn't accessible for all leads in project #864 as the screen just loads and there is a DOM error in the console.

I'm guessing this has something to do with the permission changes that happened yesterday?

Also getting a 'server error' message for some simplified text extraction after showing the 'lead processing message'. when refreshing the page, the simplified text does show, however (not sure if this is related or a separate bug)

https://beta.thedeep.io/projects/864/leads/10681/edit-entries/ [for bad loading for entires page]
https://beta.thedeep.io/projects/5/leads/10685/edit-entries/#/overview [for bad loading of simplified text]

![image](https://user-images.githubusercontent.com/9661732/54909253-0bdf2d00-4eea-11e9-9aef-a359484bc6f2.png)

![image](https://user-images.githubusercontent.com/9661732/54909305-27e2ce80-4eea-11e9-8879-842f0c7eb34a.png)

**Comment by frozenhelium** [comment]
+1 for the detailed description

**Comment by eoglethorpe** [comment]
;)

**Comment by amarshahi** [comment]
Hours Spent: 1.5 hours
