### ISSUE TITLE
Include all AF info in Tableau

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#304]
We don't need to break it out of the json format or w.e for now, but would be good to provide it. How difficult is this?

**Comment by eoglethorpe** [comment]
@amarshahi @AdityaKhatri ?

**Comment by thenav56** [comment]
@eoglethorpe Can you explain in detail?
Also, provide an expected API response.

Thanks,

**Comment by eoglethorpe** [comment]
navin ji, will follow up with more details
