### ISSUE TITLE
Sporadic bad handling of docx/doc

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#306]
Seems like some doc/docx aren't properly handle and lead to the following while tagging (in the second example the 'original' tab works, but text isn't extracted:

![image](https://user-images.githubusercontent.com/9661732/55346184-2b5df300-54b2-11e9-98de-19eac5755591.png)

![image](https://user-images.githubusercontent.com/9661732/55346197-344ec480-54b2-11e9-816a-943214bf081e.png)

Not at all working [doc]: https://beta.thedeep.io/projects/397/leads/11116/edit-entries/#/overview
Simplified not working [docx]: https://beta.thedeep.io/projects/397/leads/11118/edit-entries/#/overview
Working fine [docx]: https://beta.thedeep.io/projects/397/leads/11117/edit-entries/#/overview

**Comment by AdityaKhatri** [comment]
This took 6 hours.

**Comment by eoglethorpe** [comment]
this seems to work fine except it's throwing a server error for the following leads:

https://alpha.thedeep.io/projects/8/leads/82/edit-entries/#/overview
https://alpha.thedeep.io/projects/8/leads/81/edit-entries/#/overview
https://alpha.thedeep.io/projects/8/leads/80/edit-entries/#/overview
https://alpha.thedeep.io/projects/8/leads/79/edit-entries/#/overview

This 'server error' is resolved when refreshing the page, not sure if it's just when first viewed that it occurs.

![image](https://user-images.githubusercontent.com/9661732/55707301-909a7280-59e3-11e9-89c9-66dca02566fa.png)

there is also an issue with this lead (https://alpha.thedeep.io/projects/8/leads/81/edit-entries/#/overview) not loading original:

![image](https://user-images.githubusercontent.com/9661732/55707388-ca6b7900-59e3-11e9-94ac-c2e32d681c8c.png)
