### ISSUE TITLE
Tabular: Edit entries: bad shading of icons

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#309]

**Comment by eoglethorpe** [comment]
![image](https://user-images.githubusercontent.com/9661732/55386830-9e0db380-5530-11e9-9e55-c88597cb48ff.png)

**Comment by AdityaKhatri** [comment]
Are you talking about the white background or green selected background or icons without a white background?
We've removed the white background on our latest fix. Will this cover it?

**Comment by eoglethorpe** [comment]
yeah just the floating white box - should be fine without the bg
