### ISSUE TITLE
Export: Excel export failing

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#311]
https://beta.thedeep.io/projects/397/exports/

![image](https://user-images.githubusercontent.com/9661732/55475088-3bd9af00-5613-11e9-9200-173d72016bd5.png)

https://sentry.io/organizations/deep-of/issues/969785114/?environment=beta&referrer=alert_email&project=1223295

**Comment by bewakes** [comment]
This has been fixed and will be reflected on next deployment.

**Comment by eoglethorpe** [comment]
when’s that? what was the issue?

**Comment by bewakes** [comment]
The issue was exception was not handled well while extracting image url. It is deployed in alpha.

**Comment by amarshahi** [comment]
Hours: 1.5

**Comment by eoglethorpe** [comment]
i can't easy replicate this as it relates to a project in prod, but i'll wait to verify once this is pushed to prod

**Comment by bewakes** [comment]
@eoglethorpe, okay, will let you know
