### ISSUE TITLE
Connectors: Proper handling of bad URLs

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#312]
When either of these links are pasted as a connector, you can continue to select fields etc and test, and then the following blank warning is given.

https://www.euractiv.com/feed/
http://rss.cnn.com/rss/edition.rss

![image](https://user-images.githubusercontent.com/9661732/55476610-59107c80-5617-11e9-88a1-8395190c1f13.png)

**Comment by eoglethorpe** [comment]
what's the proposed fix here?

**Comment by AdityaKhatri** [comment]
The error was not being properly handled and shown in the error popup.
Also, the error was because of faulty access during fetch which was also fixed.

**Comment by amarshahi** [comment]
Hours: 2

**Comment by eoglethorpe** [comment]
seems like now there just isn't a warning message for either of these URLs, and just the blank 'nothing to show' table

**Comment by AdityaKhatri** [comment]
We fixed the empty error message and the reason why the error occurs.
The website is also an xml document so it doesn't throw any error.

**Comment by eoglethorpe** [comment]
gucci
