### ISSUE TITLE
Select Input: Limit display options

### ISSUE THREAD

**Issue by frozenhelium** [the-deep/deeper#314]
Cap the display options to fixed amount (100 by default) in Single and Multi Select inputs
Hours required: 10

**Comment by eoglethorpe** [comment]
@frozenhelium can you explain this behavior a bit more?

**Comment by eoglethorpe** [comment]
does it include searching done server side?

**Comment by frozenhelium** [comment]
No, server side searching for this would take a lot of time. So, for now we only implement it client side.

**Comment by tnagorra** [comment]
Fixes https://github.com/the-deep/deeper/issues/177

**Comment by eoglethorpe** [comment]
@frozenhelium ok, but you don't anticipate an impact on performance if all the data is sent clientside as long as it's not rendered?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , there won't be an impact on performance as the data listed wouldn't be that big.
Also, we do agree that a longer-term solution would be to have a server side search, but we would need significantly more time to implement that.
As this is urgent, we think we should go with client-side pre-fetch of data.

**Comment by eoglethorpe** [comment]
this behavior is approved but still waiting for an overview of where it'll be applied on the site

**Comment by AdityaKhatri** [comment]
I've created issues for them:
https://github.com/the-deep/deeper/issues/581
https://github.com/the-deep/deeper/issues/582
https://github.com/the-deep/deeper/issues/583
