### ISSUE TITLE
bulk upload - bulk delete

### ISSUE THREAD

**Issue by patricechataigner** [the-deep/deeper#316]
In the bulk upload i have loaded a bunch of document. now if i want to delete them i need to do it one by one. is it possible to implement the classic  ctrl A or ctrl shift to select several leads at the same time and do a bulk delete?

**Comment by tnagorra** [comment]
We currently do not have a ctrl+A or ctrl+Shift to select several leads.
But we can delete all leads at once using 'Remove' dropdown.

![grim_2019-04-05-125901](https://user-images.githubusercontent.com/4928045/55610425-9c4b2680-57a2-11e9-82e3-63f5b1aea4c3.png)
1. 'Selected' option will remove the lead currently being viewed.
2. 'Fileted' option will remove all the leads shown in the left pane (when filter is applied)
3. 'Saved' option will remove all the saved leads
4. 'All' option will remove all the leads

Hope this helps for now!

**Comment by eoglethorpe** [comment]
@frozenhelium @amarshahi can you give us an estimated LoE for multi select with ctrl a or shift? also if there's any way to incorporate this with other components.

**Comment by patricechataigner** [comment]
I would suggest to implement the ctrl A or Shift feature and also to allow to have little boxes on the left of all document title so we can select a few of them ( similar to what we have to select leads in the export panel).

**Comment by frozenhelium** [comment]
@eoglethorpe , if we were to make this supportable with other components as well, it would entail other cases such as multiple supported components being in same page as well. If we were to build this to be as modular as we can, it would take around 56 hours.
As we are also planning to add more features (unified connectors, better handling of bulk upload), it would take less amount of hours to do it together (24-30 hours).
To implement only on bulk upload immediately it would take around 36 hours.

**Comment by eoglethorpe** [comment]
got it tnx @frozenhelium. i personally don't think it's a priority for now unless @patricechataigner does?

**Comment by patricechataigner** [comment]
Yes not an immediate priority!
