### ISSUE TITLE
Tabular: Inconsistent appearance of  ... (is always there for sheets, only appears for columns when one has been deleted)

### ISSUE THREAD

**Issue by tnagorra** [the-deep/deeper#322]
@eoglethorpe Previously both of the '...' button would be disabled.
Then you suggested to only show the '...' button for columns when it is applicable.

Do you want to hide the '...' button for sheets as well when it is not applicable?

One concern is that when the button is shown/hidden, the sheet tabs will move from it's place.
What do you suggest?

**Comment by eoglethorpe** [comment]
ok to keep the button for both columns and sheets but disable/grey out the button when it's not applicable (this also means making the button not clickable)
