### ISSUE TITLE
AnalysisFramework: Add a button to clone certain widget

### ISSUE THREAD

**Issue by tnagorra** [the-deep/deeper#34]

**Comment by eoglethorpe** [comment]
@AdityaKhatri would you be able to provide me with an estimate on this? (pls tag me in the response)

**Comment by AdityaKhatri** [comment]
@eoglethorpe , for the behavior:
1. `clone` button appears beside `edit` button
2. After clicking `clone` new widget with cloned values is created
3. Title of cloned widget is `{old_widget_name}(cloned)`

It will take 64 hours.
If we skip cloning for conditional widget, it will be 44 hours.

**Comment by eoglethorpe** [comment]
@AdityaKhatri 64h? damn. what's the reason for that?

**Comment by AdityaKhatri** [comment]
Hi @eoglethorpe , there are a variety of widgets in the system, which all have different structures with different levels of complexity. In almost all of them, we have 'addable' items which are a unique key-value pair. For each key, we need to create a new unique key. For that reason, the each widget is treated differently and we need to write a traverse algorithm separately for them and also test them thoroughly.
Conditional widgets are more difficult as they have widgets among them, which requires more testing and trials.
