### ISSUE TITLE
Export: Add thousand separator for numbers

### ISSUE THREAD

**Issue by tnagorra** [the-deep/deeper#343]

**Comment by thenav56** [comment]
@eoglethorpe Should we use 1K 1M instead?

**Comment by eoglethorpe** [comment]
@thenav56 what exactly do you mean?

**Comment by thenav56** [comment]
@eoglethorpe Similar to this.

**Comment by thenav56** [comment]
@eoglethorpe Similar to this. ![grim_2019-04-10-210651](https://user-images.githubusercontent.com/7059255/55891642-a3c06480-5bd4-11e9-8777-6a85a0fdcfc7.png)

**Comment by eoglethorpe** [comment]
@thenav56 oooo very nice, yes i'm game with that

**Comment by thenav56** [comment]
@eoglethorpe It's the current behavior.

**Comment by eoglethorpe** [comment]
@nav

**Comment by thenav56** [comment]
@eoglethorpe Right now. It's normal. We can add comma separator there if you want.
![grim_2019-04-17-083209](https://user-images.githubusercontent.com/7059255/56257261-620b4e80-60eb-11e9-9cb3-8bfee95856f6.png)

**Comment by eoglethorpe** [comment]
ah cool. yes thousands separator!!!!!!

**Comment by thenav56** [comment]
@eoglethorpe Sweet, it will look like this with thousands separator and SI Prefix.
![grim_2019-04-17-082904](https://user-images.githubusercontent.com/7059255/56285633-678e8600-6137-11e9-8e53-5aa1e46cb23a.png)

**Comment by eoglethorpe** [comment]
bravo!
