### ISSUE TITLE
AddLead: If url does't start with https:// or http:// url preview doesn't work

### ISSUE THREAD

**Issue by tnagorra** [the-deep/deeper#38]
Currently a url without "https://" or "http:" is detected as invalid url by the regex test

**Comment by eoglethorpe** [comment]
@AdityaKhatri @tnagorra can you please explain this?

**Comment by tnagorra** [comment]
Url without `http://` or `https://` prefix is not valid anywhere in the platform.
This pull request will change that and url without those prefix will be assumed to have a `http://` prefix and be accepted.

So, the form validation will pass and the preview will also be shown.

**Comment by eoglethorpe** [comment]
sweet, thanks!

**Comment by AdityaKhatri** [comment]
@eoglethorpe , as discussed, there will be some server side work on this issue.
The total amount of work needed would be 8 hours (server side) + 3 hours (client side).
