### ISSUE TITLE
Export: full Excel export not completing

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#558]
*Without changing any filters, do the Excel export. 
*Doesn't complete. (unselecting decoupled doesn't make any difference - although it does work if I filter)

https://beta.thedeep.io/projects/878/exports/
![image](https://user-images.githubusercontent.com/9661732/55961191-9ce63000-5c6e-11e9-981d-2d67c6d250a7.png)

**Comment by pprabesh** [comment]
@eoglethorpe This was the error with the export queue issue what Patrice mentioned in the slack. It was fixed the same day.

I tried and the export is working now. Let me know if this still exits.

**Comment by eoglethorpe** [comment]
ok cool, thanks
