### ISSUE TITLE
AF: Enable export of framework

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#590]
To PDF, jpeg, svg.

would need to consider how to show values from dropdown lists, sub dimensions etc

**Comment by AdityaKhatri** [comment]
@eoglethorpe , let us know if you have any ideas on how to show values from dropdown lists and sub-dimensions.

**Comment by eoglethorpe** [comment]
@AdityaKhatri i think for both we'd have to display it as if all the values has been selected (i know this may create some weird looks). could be good to see what this would look like for some common frameworks. 

your thoughts?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , that will work for list widgets, but not for sub-sectors.
I think we need to export them a bit differently rather than taking a screenshot.
I'll discuss this with the whole team including our designer.
Let us know if there is a cap in the hours.

**Comment by eoglethorpe** [comment]
@AdityaKhatri cool - why not for subsectors? would be interested in hearing your ideas.

no fixed cap for hours but it'd be coming from general maintenance funds so would need to kept to a minimum. please let me know before you start doing anything billable on it.

**Comment by AdityaKhatri** [comment]
![image](https://user-images.githubusercontent.com/7893887/67921647-75d25a00-fbd0-11e9-8eff-74f5d29d5fca.png)

For sub-sectors we don't have lists so if we select more than what the placeholder can contain, it will be cut off.

**Comment by eoglethorpe** [comment]
fair point. lemme know what you guys come up with as a workaround?
