### ISSUE TITLE
Edit AF: Bug on focus for new rows in 1D matrix

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#594]
When you add a row in 1D matrix, the default focus is on the tooltip, should be on title

![image](https://user-images.githubusercontent.com/9661732/58713559-d135bd00-8390-11e9-8e58-53655c38ccc9.png)

**Comment by tnagorra** [comment]
@eoglethorpe do you mean matrix 2d?

**Comment by pprabesh** [comment]
Hours: 1
