### ISSUE TITLE
xls upload still gives error

### ISSUE THREAD

**Issue by pprabesh** [the-deep/deeper#595]
Do we support xls @thenav56 ?

**Comment by thenav56** [comment]
@eoglethorpe, Until now DEEP doesn't support XLS. Behavior is as excepted.

**Comment by eoglethorpe** [comment]
@AdityaKhatri @frozenhelium XLS is mentioned in the spec doc?

**Comment by eoglethorpe** [comment]
didn't we talk about xls awhile ago and end supporting it? i can't remember
