### ISSUE TITLE
For this data attribute the following chart is generated, and i don’t understand on the x axis why the bar takes up mutltiple values

### ISSUE THREAD

**Issue by thenav56** [the-deep/deeper#604]
![image](https://user-images.githubusercontent.com/7059255/58853570-7e267780-86ba-11e9-8ad2-35adb754d0ed.png)

**Comment by thenav56** [comment]
@eoglethorpe Plotly is rendering bar using available space(2 points) and the ticks are in the interval for the given points. We can treat DateTime as string entirely as below (without date interval ticks).
Is this as expected?

![image](https://user-images.githubusercontent.com/7059255/58867648-8bebf500-86da-11e9-81d9-a1cf1aa03087.png)

![image](https://user-images.githubusercontent.com/7059255/58867685-9c9c6b00-86da-11e9-9ba5-b1b8457629c4.png)

**Comment by thenav56** [comment]
@eoglethorpe Or you want line graph. Something like this?

![image](https://user-images.githubusercontent.com/7059255/58868017-33692780-86db-11e9-9a90-e24786b011f3.png)

![image](https://user-images.githubusercontent.com/7059255/58868025-382ddb80-86db-11e9-8983-cd9c67d0c335.png)

**Comment by eoglethorpe** [comment]
@thenav56 can we keep it as bar graphs with the minimal ticks like you've shown?

i don't think we should treat dates as strings, as then it gets too busy as you've shown in that example. can we do as is shown in `Colored and Styled Bar Chart` on https://plot.ly/python/bar-charts/ where when there are many dates they become 'grouped'?

**Comment by thenav56** [comment]
@eoglethorpe Not sure how we will do the grouping (group the data) as you suggested.
We can also change the behaviors when there are few data points (where the main problem exists).

![image](https://user-images.githubusercontent.com/7059255/58932832-f9546000-8784-11e9-84d2-4c1a84cd0af3.png)

And no change for a higher number of data points.
![image](https://user-images.githubusercontent.com/7059255/58932845-04a78b80-8785-11e9-8625-d3221994fdcb.png)
