### ISSUE TITLE
AF: Add filters in AF options listing

### ISSUE THREAD

**Issue by frozenhelium** [the-deep/deeper#610]
- Active: A framework is active if it is used by at least one project which is active.
- Inactive: All other framework which is not “Active” 
- Frameworks related to user (Wording to be decided)
-- All the frameworks created by that user
-- All the frameworks which is used by projects that the user is part of.
- All

**Comment by frozenhelium** [comment]
Hours: 30

**Comment by eoglethorpe** [comment]
I think we should simplify this down to:

-Active: A framework is active if it is used by at least one project which is active.
-Inactive: All other frameworks which are not “Active”
-My Frameworks: All frameworks related to user (projects they're members of etc - would need to flesh this out a bit more)
-Created By Me: ones created by user
-All: All

**Comment by frozenhelium** [comment]
![af-filters](https://user-images.githubusercontent.com/4931541/59246907-7415f300-8c3d-11e9-836c-1219b94879a1.png)
@eoglethorpe Mockup for the filters

**Comment by eoglethorpe** [comment]
@frozenhelium just talked with PC and i think we could simplify this by one lining it. I propose:

We keep the multi select as is (although change order to All | Active | Inactive) and then a checkbox called "Mine"

**Comment by eoglethorpe** [comment]
Or perhaps "Related". We can make the column a bit wider to accommodate?

**Comment by frozenhelium** [comment]
Sure will try it out

**Comment by frozenhelium** [comment]
![af-filters-revised](https://user-images.githubusercontent.com/4931541/59332712-9760a100-8d16-11e9-8eb5-1a19fa31cd89.png)
@eoglethorpe Something like this?

**Comment by eoglethorpe** [comment]
Nice! Do you think "Related to me" would fit? if you had it on two lines? no worries if not

**Comment by frozenhelium** [comment]
@eoglethorpe We can slightly increase the width to fit the text "Related to me".

Also while doing this we came across a quick optimization in the request for framework list, which will somewhat reduce the time it takes to query the values and will require around 4 hours of additional work, shall we proceed with that?

**Comment by eoglethorpe** [comment]
k00l per our call
