### ISSUE TITLE
Tabular: Histogram doesn't treat 0 as value

### ISSUE THREAD

**Issue by thenav56** [the-deep/deeper#675]
Current behavior,
![grim_2019-06-20-164726](https://user-images.githubusercontent.com/7059255/59844749-594d2800-937b-11e9-8a22-333cbe9760a4.png)

Excepted behavior, @eoglethorpe this is excepted right? 
![grim_2019-06-20-164855](https://user-images.githubusercontent.com/7059255/59844766-5fdb9f80-937b-11e9-857d-2e4d082fa288.png)

**Comment by eoglethorpe** [comment]
@thenav56 yes this looks fine, but could we zoom out the horizontal axis? similar to this 
![image](https://user-images.githubusercontent.com/9661732/59867919-7c68df00-935d-11e9-890f-62dfae5631a8.png)
