### ISSUE TITLE
Leads: Apply delete action to multiple leads [OHCHR request]

### ISSUE THREAD

**Issue by frozenhelium** [the-deep/deeper#70]
Add delete action, and multiselect from multiple pages.

Talk with @Mariam-Asatryan for the behavior of selection through multiple pages.

**Comment by eoglethorpe** [comment]
@Mariam-Asatryan we'd like to be able to apply actions to multipel leads at onec in the leads page. do you think we'll signficantly modify this page, and should hold off?

**Comment by mariam-yu** [comment]
@eoglethorpe I think one way or another we will have to have a place where you see the list of all the leads. So, I think it's a good idea, especially if we add inline editing. Do you have the specific user case for what kind of functionality they would apply in bulk?

**Comment by eoglethorpe** [comment]
yeah, i'd say just move to another project and delete?

**Comment by mariam-yu** [comment]
@eoglethorpe It makes sense. So probably something like gmail approach could be good - quite standard. Let me know if you need anything else.
<img width="191" alt="Screen Shot 2020-09-25 at 12 22 38 PM" src="https://user-images.githubusercontent.com/60006476/94256292-e3dee880-ff29-11ea-8d64-768e4d79bc8c.png">
<img width="529" alt="Screen Shot 2020-09-25 at 12 22 45 PM" src="https://user-images.githubusercontent.com/60006476/94256306-e9d4c980-ff29-11ea-972c-9e932028849a.png">

**Comment by eoglethorpe** [comment]
hm, what exactly do you mean @Mariam-Asatryan ?

**Comment by mariam-yu** [comment]
@eoglethorpe proposed a way it could work potentially unless you guys already have it set up. Like to do a multi-select just like in gmail and if extra bulk functionalities are needed, they can show up when multiple items are selected. Let me know if this makes sense.

**Comment by mariam-yu** [comment]
@frozenhelium just saw the text above about it being selected through multiple pages. How does that work?

**Comment by AdityaKhatri** [comment]
@mariam-yu , the multiple pages is the behavior I showed you on our previous call.
We can select items through multiples pages while doing pagination.
