### ISSUE TITLE
Browser warning for non-chromium browsers

### ISSUE THREAD

**Issue by frozenhelium** [the-deep/deeper#79]

**Comment by eoglethorpe** [comment]
@frozenhelium what's the level of effort here? can we do this on this month's maintenance?

**Comment by frozenhelium** [comment]
This is a complicated mechanism and not a one time thing to do. It'll require very frequent update because the mechanism to detect browser changes with the update in browser.

**Comment by eoglethorpe** [comment]
i see - but we wouldn't need to maintain the browser recognition logic ourselves would we? wouldn't that be taken care of by an actively maintained library?

**Comment by tnagorra** [comment]
Yes, we won't need to maintain the browser recognition logic ourselves.
But we would need to timely update the library in DEEP and deploy accordingly.
So we may have a time lag between the library update and deployment.

**Comment by eoglethorpe** [comment]
got it - well i mean i'd rather have us be a bit behind on a release and capture 80% of bad visits as opposed to 0, so if we could pls proceed with this and have a plan for tracking when new libraries are released

**Comment by AdityaKhatri** [comment]
@eoglethorpe , let us know which behavior you want to implement:

1. Show warning for non-chrome browsers in every page
    * Warning should be dismiss-able.
      1.1 Remember dismiss action for browser
        OR
      1.2 Remember dismiss action for the user

OR

2. always show warning for non-chrome browser in the login page

**Option 1.1**: 48 hours
**Option 1.2**: 48 hours
**Option 2**: 40 hours

**Comment by eoglethorpe** [comment]
User story: Users who don't use Chrome don't know it's not compatible with DEEP so they see a weird version of the site with reduced functionality.

AC: 
* Red banner on top of the page reading "Hey DEEP user - it seems you're not using Google Chrome as your browser! DEEP is only supported on the latest versions of Chrome, which you can download here <https://www.google.com/chrome/>. If you continue using your browser, you may face some unexpected issues.".
 * Could we also put up the Chrome logo or similar?
* Banner is dismissible for browser (don't worry about user)... is this about the same LoE?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , this is the current view. Where do you want the chrome logo?
![image.png](https://zube.io/files/deep/6542966b7e31096bf800df445d19b4c9-image.png)

**Comment by eoglethorpe** [comment]
looks nice! and good to hear about the library.

as for the Chrome image, i think we can just skip it. however, could we move the X to the far right hand corner?
