### ISSUE TITLE
Select Input: Wrap text during small width

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/deeper#869]
![image](https://user-images.githubusercontent.com/7893887/67259574-4a57bd00-f4b6-11e9-8446-537bbbd8caf7.png)

**Comment by AdityaKhatri** [comment]
@eoglethorpe , right now the words will wrap but not letters.
Should we proceed with wrapping letters as well?

**Comment by eoglethorpe** [comment]
@AdityaKhatri what do you mean exactly?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , that would mean the word 'confidential' breaking down into 'confid' and 'ential' in the next line.

**Comment by eoglethorpe** [comment]
hey @AdityaKhatri sorry i missed this. still ongoing?

**Comment by AdityaKhatri** [comment]
Yeah, we haven't worked on this.
Let me know if we need to put it in our immediate backlog.
