### ISSUE TITLE
Edit Ary: Stakeholder's view layout

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/deeper#870]
![image](https://user-images.githubusercontent.com/7893887/67454807-54f78b00-f64b-11e9-8118-a00203d99bb1.png)

- can we align the first category with the DATA COLLECTION START DATE header?
- make the differentiation between the headers (ie LEAD ORG) and the actual orgs a bit more obvious?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , we'll look into it.

**Comment by eoglethorpe** [comment]
tnx @AdityaKhatri
