### ISSUE TITLE
Bug: word cloud component fails

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#886]
Clicking sentry doesn't prompt a reporting window either, but i believe it's this sentry error: https://sentry.io/organizations/deep-of/issues/1593860531/?environment=beta&referrer=alert_email

bug occured for this document: https://beta.thedeep.io/projects/397/leads/11119/edit-entries/#/overview - you guys can add yourself to the project if you're not in it.

for #hybrid_municipal_pct (other columns seem to work fine)

![image](https://user-images.githubusercontent.com/9661732/78263435-f2df6380-74cf-11ea-8dde-62c4c4430607.png)

**Comment by eoglethorpe** [comment]
@AdityaKhatri could you guys please work on this?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , this tabular seems to be of the old version (while it was in testing phase), hence the cache for these were not updated.
We retriggered the tabular creation for this lead and it looks like it has been fixed.

**Comment by eoglethorpe** [comment]
ah cool, thanks
