### ISSUE TITLE
cat editor: pulling images in gallery

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#890]
![image](https://user-images.githubusercontent.com/9661732/81222939-2459bc00-8fb3-11ea-8911-18bb6e4e1063.png)

can you please explain how this happening and what happened from when this was fixed preivously? for project board demo

**Comment by AdityaKhatri** [comment]
Hi @eoglethorpe , by this do you mean the list of images that are appearing?

**Comment by AdityaKhatri** [comment]
Discuss during refinement with the whole team
