### ISSUE TITLE
Analysis Framework: Export in jpeg

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/deeper#900]

**Comment by AdityaKhatri** [comment]
@eoglethorpe , for framework exports, I've attached 2 images.
The library we are currently using for exporting to jpeg is html2canvas, and it looks like it doesn't support the rotated text. Is that fine?
Also, do you want some demarcation between the overview and list elements?

![export-Clone of Pika (1).png](https://zube.io/files/deep/606a32e6d67a01ea862f86b00e738d2c-export-clone-of-pika-1.png)![export-Pika for bulbasaur.png](https://zube.io/files/deep/f43151cdad5605e9564b3df758635019-export-pika-for-bulbasaur.png)

**Comment by eoglethorpe** [comment]
@AdityaKhatri no need to worry about the demarcation if it's more complicated.

also not the end of the world if the rotated text is too complicated.

i would, however, say that we'd like to see the values for the additional widgets (i.e. drinks/food options don't show the values). is it possible to see those? also, wondering about extreme cases with a large amounts of values in drop downs and howe that would look?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , sounds good on the demarcation. The demarcation is not complicated.
Regarding the ability to see the values, I don't think we can put all of them in the screenshot where it would look okay for all different kinds of frameworks.
The best way to show the list values would be through a separate excel export.

**Comment by AdityaKhatri** [comment]
@eoglethorpe , here is the latest one with demarcation.
![export-Clone of Pika (4).png](https://zube.io/files/deep/504f008784709490bcefb62d3190b510-export-clone-of-pika-4.png)

**Comment by AdityaKhatri** [comment]
Currently cutoff at the bottom
