### ISSUE TITLE
Record file size

### ISSUE THREAD

**Issue by frozenhelium** [the-deep/deeper#907]

**Comment by AdityaKhatri** [comment]
Related to: https://zube.io/deep/deep/c/358

**Comment by eoglethorpe** [comment]
AC: 

- new column showing file size where there are attachemnts
- where there are no attachemnts, leave blank
- @Mariam-Asatryan how do you want to bucket file sizes?

**Comment by eoglethorpe** [comment]
<waiting for patrice response>

**Comment by eoglethorpe** [comment]
@AdityaKhatri are we currently recording file sizes in the DB?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , no we don't.

**Comment by AdityaKhatri** [comment]
This is best done after connectors is completed.

**Comment by jbbove** [comment]
@AdityaKhatri just to be sure, here the file size will not be shown to the users since we already have the pages, this data will be recorded but not shown right?

**Comment by AdityaKhatri** [comment]
Patrice requested to have it on the leads table as well, its fine with us either way.

**Comment by eoglethorpe** [comment]
I believe we decided to just record it and not put it on the table for now

**Comment by thenav56** [comment]
PR: https://github.com/the-deep/server/pull/581

Already started the script in production. We are only calculating and storing the file size in the database.
