### ISSUE TITLE
Add Lead: Visual cue for drag and drop

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/deeper#918]
When a user drags a folder/file over DEEP, it should indicate that it accepts drop behavior in add leads page.

**Comment by frozenhelium** [comment]
Need more details @AdityaKhatri

**Comment by AdityaKhatri** [comment]
@frozenhelium ,
When dragging over the page, we need to let the users know where it can be dropped.

**Comment by AdityaKhatri** [comment]
@AdityaKhatri to write a description after this.
