### ISSUE TITLE
Screenshot: Allow for highlight using brush/pen tool

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/deeper#925]
1. Draw over the screenshot.
2. Have clear action.
3. Converted to the image after.
4. Different size brushes and different colors.
5. Support eraser.

**Comment by AdityaKhatri** [comment]
@Mariam-Asatryan , here are the screenshots you requested.
Let me know if you need anything else.

![image.png](https://zube.io/files/deep/bc46e6e61d4d724ac6f1ca596a7dc252-image.png)
![image.png](https://zube.io/files/deep/210e56d050fed8f09ed6aed5a5c40bec-image.png)

**Comment by mariam-yu** [comment]
@AdityaKhatri Thanks for sharing these. So, I'd say the functionality is pretty good and clear. We will need to make more explicit icons, action bar, etc. But that will come with the UI library. In the meantime, may be worth replacing the brush with something else more explicit, like:

![Screen Shot 2020-09-29 at 11.21.35 PM.png](https://zube.io/files/deep/39df326586f2f72c32fa4500eb750e66-screen-shot-2020-09-29-at-11-21-35-pm.png)

Not sure if this works. Also the action items are a bit too small.

Lastly, when you are in the edit view, do we need to go full-screen with the screenshot centered and action items quite far? May be worth making it much more around the screenshot size itself with of course enough space for the functionalities. This way Done and Cancel can be closer and more visible too. We will tackle those in the UI library too.

Please let me know if this makes sense. Thanks!

**Comment by AdityaKhatri** [comment]
Thanks @Mariam-Asatryan , we'll work on the icons and try to work on the modal was well.
