### ISSUE TITLE
plus button for tagging

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#941]

**Comment by AdityaKhatri** [comment]
@eoglethorpe , could you provide more details on this?
Which page are you referring to and what will be the behavior?

**Comment by eoglethorpe** [comment]
US: it's cumbersome to do the select text and drag and drop 
AC: after users highlight text in the tagging page, a 'plus' button should appear near the highlight and when clicked, it will create a new entry with that text as the entry text

**Comment by AdityaKhatri** [comment]
Research on ways we can add '+' button next to the text and talk with @Mariam-Asatryan  based on options and decide further.

**Comment by frozenhelium** [comment]
@Mariam-Asatryan We've researched a bit on this and we can do something similar to the following:
![2020-10-07-172316.png](https://zube.io/files/deep/3a1adab3f961e95bb2251f170febd6db-2020-10-07-172316.png)

**Comment by AdityaKhatri** [comment]
Discussed with @Mariam-Asatryan and @eoglethorpe to include the action popup at bottom of the text instead of top.
