### ISSUE TITLE
Backend research of lnex integration

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#944]
AC: An outline of how lnex can be integrated on the backend

Things we need to research:
1. Lnex's output and feasibility in DEEP
2. DEEPL integration with DEEP

**Comment by AdityaKhatri** [comment]
@eoglethorpe , what would we use lnex for?

**Comment by AdityaKhatri** [comment]
To do:
Setup a test instance to see how we can interact with LNEX

**Comment by annshress** [comment]
We can setup a background service in deep that will grab excerpts from entries and geo tag them appropriately.

Currently a sample is deployed at http://3.23.100.189:5000/, which will return with extracted geo location and its geo info.

Sample request: `curl 3.23.100.189:5000 -d "q=#ChennaiFloods  All #trains to and from Chennai Central and Chennai Egmore #cancelled till 12 hrs on Dec5, says SouthernRailway&bb=c"`
