### ISSUE TITLE
Mailchimp for email notifications

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#950]
Awhile back we talked about putting notification emails through Mailchimp. Coudl you guys look into the viability of this?

@matthew-oglethorpe , not sure how to best address this on the board?

**Comment by AdityaKhatri** [comment]
@eoglethorpe , this is good.
Lets label this as a spike task and we can come out with how this can be used in DEEP.

**Comment by AdityaKhatri** [comment]
@jbbove , could you follow up with Ewan on this?
