### ISSUE TITLE
Add project wise feature access

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/deeper#959]

**Comment by frozenhelium** [comment]
@AdityaKhatri @tnagorra We currently have user wise features which is currently being pulled along with user details. I propose we create similar functionality in the project. So, when fetching a project, user will get list of the accessible features to the project.

**Comment by frozenhelium** [comment]
We decided to modify and use existing `Feature` model in `User` app to support projectwise features. 
CC: @Navin-Ayer @tnagorra @annshress @AdityaKhatri
