### ISSUE TITLE
Communicate extra data with error

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/deeper#962]

**Comment by thenav56** [comment]
@tnagorra @AdityaKhatri . Does this works?

![2020-11-06-114921.png](https://zube.io/files/deep/d1977a83f8f7efd58ff456a082fd80eb-2020-11-06-114921.png)

**Comment by AdityaKhatri** [comment]
Works for me @Navin-Ayer .
@tnagorra , waiting for your feedback.

**Comment by tnagorra** [comment]
Yes, should work!

**Comment by tnagorra** [comment]
Previously, we have this schema for errors:
```
{
   errors: { non_field_errors: ["error", "some error"], some_other_field: "string", yet_another_field: "string" }
}
```

To add data to what error we have, we should update `non_field_errors` to include objects:
```
{
   errors: { non_field_errors: [{ message: "error": leads: []}], some_other_field: "string", yet_another_field: "string" }
}
```
